modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/embellishcraft/issues"
[[mods]]
modId="embellishcraft"
version="${file.jarVersion}"
displayName="EmbellishCraft"
#updateJSONURL="http://myurl.me/"
displayURL="http://mapper.tv/embellishcraft/"
logoFile="embellishcraft_logo.png"
credits="The Forge team and community for the help and resources."
authors="Mapper"
description='''EmbellishCraft is a mod that adds various decorative elements to Minecraft.'''

[[dependencies.embellishcraft]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="mapperbase"
    mandatory=true
    versionRange="[1.16.3-2.1.,)"
    ordering="AFTER"
    side="BOTH"