modLoader="javafml" #mandatory
loaderVersion="[27,)"
issueTrackerURL="http://my.issue.tracker/" #optional
logoFile="embellishcraft_logo.png" #optional
[[mods]] #mandatory
modId="embellishcraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="EmbellishCraft" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://mapper.tv/embellishcraft/" #optional
credits="Thanks for Forge devs and modders that let their mods open-source." #optional
authors="Mapper" #optional
description='''EmbellishCraft is a mod that adds various decorative elements to Minecraft.'''

[[dependencies.embellishcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27.,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"